openapi: 3.1.0
info:
  title: Screen Api
  description: Screen Api
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /display/{id}:


components:
  schemas:
    emergency:
      required:
        - text
      properties:
        text:
          type: string
        timeout:
          type: string
          format: date-time

    block:
      required:
        - title
        - text
      properties:
        type:
          type: string
          enum: [news, info, parking, storages]
        title:
          type: string
        text:
          type: string
        date:
          type: string
        images_url:
          type: array
          items: integer

    styles:
      type: string

    event:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum: [putBlock, putEmergency, disableEmergency]
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/block'
        emergency:
          type: string